apiVersion: v1
kind: ConfigMap
metadata:
  name: elk-elasticsearch-config
  namespace: k3s-elk
  labels:
    app: elk-elasticsearch
    component: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: k3s-elasticsearch-cluster
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: false
    xpack.security.http.ssl.enabled: false
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
