apiVersion: v1
kind: ConfigMap
metadata:
  name: elk-logstash-pipeline
  namespace: k3s-elk
  labels:
    app: elk-logstash
    component: logstash
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json_lines
      }
    }
    filter {
      if [message] {
        json {
          source => "message"
        }
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elk-elasticsearch-0.elk-elasticsearch-headless.k3s-elk.svc.cluster.local:9200"]
        index => "logs-%{+YYYY.MM.dd}"
      }
      stdout {
        codec => rubydebug
      }
    }
